<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Generic.WhiteSpace.ScopeIndent.IncorrectExact
// phpcs:disable Magento2.Security.LanguageConstruct.DirectOutput
?>
<?php
    $_category  = $block->getCurrentCategory(); // return a instance of \Magento\Catalog\Model\Category object
    $_imgHtml   = '';
    // dd($_category->getThumbAttribute());
    if ($_imgUrl = $_category->getThumbAttribute()) {
        $_imgHtml = '<div class="category-image"><img src="'
            . $block->escapeUrl($_imgUrl)
            . '" alt="'
            . $block->escapeHtmlAttr($_category->getName())
            . '" title="'
            . $block->escapeHtmlAttr($_category->getName())
            . '" class="thumb_attribute" /></div>';
        // $_imgHtml = $block->getOutput()->categoryAttribute($_category, $_imgHtml, 'thumb_attribute');
        /* @noEscape */ echo $_imgHtml;
    }
?>